### PR TITLE
updated node version for github actions

### LINKED ISSUE #1561: Update Release Notes to use Node v16
### Description

We have a Github Action to generate our release notes, which uses Node 12. That will soon be deprecated by Github (see more [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/))

This issue is mentioned as an annotation on this job: https://github.com/buildpacks/pack/actions/runs/3558882069

### Proposed solution

We should do one of two things: 
* Upgrade the action to use Node 16, if that is easy

Alternatively, or in addition, we may want to investigate using another public action for generating release notes, which doesn't seem like a core part of our workflow (and can therefore be better done by another action). 

### Additional context

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=84YnEb3)
Signed-off-by: SaumyaBhushan [saumya@knoldus.com](mailto:saumya@knoldus.com)
## Summary

updated node version for github actions
#### Before
Node 12
#### After
Node 16
## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

## Related

https://github.com/buildpacks/pack/issues/1561
Resolves #1561

### CODE REVIEW

**Comment by SaumyaBhushan** [comment]
Hi @samj1912 Can you please review this one as well?

**Comment by samj1912** [comment]
@SaumyaBhushan did you have a chance to test this and see if it works with node16?

**Comment by SaumyaBhushan** [comment]
> @SaumyaBhushan did you have a chance to test this and see if it works with node16?

No I have not

**Review by SaumyaBhushan — COMMENTED** [review]
ok

**Review by dfreilich — APPROVED** [review]
Thanks for the help! 

Validated here: https://github.com/buildpacks/pack/issues/1561#issuecomment-1382606279

**Comment by SaumyaBhushan** [comment]
Hi @dfreilich Are we planning to merge this one or do we need to change something here ?

**Comment by natalieparellano** [comment]
The previous CI failures appear to be flakes. Hopefully this goes green with the latest updates from `main`

**Pull request merged**
