### PR TITLE
Add support for RegistryLocator in package-buildpack command

### PR DESCRIPTION
**Pull request by jkutner**
## Summary

Allows the use of `RegistryLocator` values in `package.toml`. For example:

```
[[dependencies]]
uri = "urn:cnb:registry:jkutner/minecraft"
```

#### Before

```
$ pack package-buildpack --config package.toml
ERROR: unsupported locator type RegistryLocator
make: *** [package] Error 1
```

(sidenote: this is not a very helpful error message)

#### After

```
$ pack package-buildpack --config package.toml
Warning: Command pack package-buildpack has been deprecated, please use pack buildpack package instead
docker.io/heroku/procfile-cnb@sha256:3c03bb4a86317d2530b91f1f2f9f75161b744016870808cb395f46cc244b8be1: Pulling from heroku/procfile-cnb
4046c360d55b: Pull complete 
Digest: sha256:3c03bb4a86317d2530b91f1f2f9f75161b744016870808cb395f46cc244b8be1
Status: Downloaded newer image for heroku/procfile-cnb@sha256:3c03bb4a86317d2530b91f1f2f9f75161b744016870808cb395f46cc244b8be1
Successfully created package jkutner/web-tty:latest
```

## Documentation

- Should this change be documented?
    - [x] Yes, see #___
    - [ ] No

## Related

Resolves #___

### CODE REVIEW

**Review by dfreilich — COMMENTED** [review]
For confidence, would you mind also adding in a test that verifies that it works even if you don't pass in a registry with the `--registry` flag? It definitely should work, but it would be nice to have the redundancy in tests.

**Comment by jkutner** [comment]
@dfreilich I'm not sure I follow. You mean a test for `internal/commands/package_buildpack_test.go` that omits the `--registry` flag and confirms it's pass through to the `BuildpackPackager`? 

The `pack.PackageBuildpack` command requires `PackageBuildpackOptions.Registry` if it a`RegistryLocator` is used (i.e. there's no default)

**Comment by dfreilich** [comment]
I think that there is a default. The code as is calls `(client) .getRegistry()`, which returns the default registry if an empty string is provided: 
https://github.com/buildpacks/pack/blob/99ada472d03f985f8209a27a345b132d88e986b9/common.go#L60-L86

**Comment by jkutner** [comment]
@dfreilich it feels like would really be testing the `pack.getRegistry()` func, which already has coverage. In fact, if it was part of an interface, I'd probably mock that part out.

**Comment by dfreilich** [comment]
Ya that totally makes sense, I hear that.

**Comment by jkutner** [comment]
It would be great to get this and #1017 in 0.16.1

**Review by dfreilich — APPROVED** [review]
# UA
```
$  out/pack buildpack package jkutner/web-tty -c /tmp/web-tty-buildpack/package.toml
Downloading from https://cnb-shim.herokuapp.com/v1/heroku/python?api=0.4&version=0.4.0&name=Python&stacks=heroku-18,io.buildpacks.stacks.bionic
3.37 MB/-1 B
docker.io/heroku/procfile-cnb@sha256:3c03bb4a86317d2530b91f1f2f9f75161b744016870808cb395f46cc244b8be1: Pulling from heroku/procfile-cnb
4046c360d55b: Pull complete
Digest: sha256:3c03bb4a86317d2530b91f1f2f9f75161b744016870808cb395f46cc244b8be1
Status: Downloaded newer image for heroku/procfile-cnb@sha256:3c03bb4a86317d2530b91f1f2f9f75161b744016870808cb395f46cc244b8be1
Successfully created package jkutner/web-tty
```

```
 $  out/pack buildpack package jkutner/web-tty -c /tmp/web-tty-buildpack/package.toml -r official
Downloading from https://cnb-shim.herokuapp.com/v1/heroku/python?api=0.4&version=0.4.0&name=Python&stacks=heroku-18,io.buildpacks.stacks.bionic
3.37 MB/-1 B
docker.io/heroku/procfile-cnb@sha256:3c03bb4a86317d2530b91f1f2f9f75161b744016870808cb395f46cc244b8be1: Pulling from heroku/procfile-cnb
Digest: sha256:3c03bb4a86317d2530b91f1f2f9f75161b744016870808cb395f46cc244b8be1
Status: Image is up to date for heroku/procfile-cnb@sha256:3c03bb4a86317d2530b91f1f2f9f75161b744016870808cb395f46cc244b8be1
Successfully created package jkutner/web-tty
```

**Pull request merged**
