### PR TITLE
Don't create an ephemeral builder if it isn't truly needed

### PR DESCRIPTION
**Pull request by natalieparellano**
Fixes https://github.com/buildpacks/pack/issues/2195

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [ ] No

## Related

Resolves #___

### CODE REVIEW

**Comment by jjbustamante** [comment]
Do we have an acceptance test covering this scenario? The only thing that comes to my mind is we are not trying to save the  ephemeral builder at some point during the build and we end up introducing some bug

**Review by jjbustamante — APPROVED** [review]
LGTM

My only concern is to double-check the acceptance test coverage

**Comment by natalieparellano** [comment]
> Do we have an acceptance test covering this scenario?

I didn't add an explicit test for this, because I am lazy (and also because our current suite is long enough) but the tests were failing before I added https://github.com/buildpacks/pack/pull/2196/commits/423f59667110a4c602955debf835a6b15220de57 because we were cleaning up the original builder, making it unavailable for other tests.

**Comment by jjbustamante** [comment]
> > Do we have an acceptance test covering this scenario?
> 
> I didn't add an explicit test for this, because I am lazy (and also because our current suite is long enough) but the tests were failing before I added [423f596](https://github.com/buildpacks/pack/commit/423f59667110a4c602955debf835a6b15220de57) because we were cleaning up the original builder, making it unavailable for other tests.

Then I am ok with it

**Pull request merged**
