### PR TITLE
Suggest/trust `heroku/builder:20` instead of `heroku/buildpacks:20`

### PR DESCRIPTION
**Pull request by edmorley**
The `heroku/buildpacks:20` builder has been superseded by `heroku/builder:20`, and the old builder is about to be deprecated:
https://github.com/heroku/cnb-builder-images/pull/394
https://github.com/heroku/cnb-builder-images/blob/main/README.md

As such, the suggested/trusted builders list has been updated accordingly.

I've also tweaked the Heroku builder descriptions to:
- mention the underlying Linux distro
- fix the alphabetical ordering of supported buildpack languages

### CODE REVIEW

**Comment by edmorley** [comment]
CI is failing in ways that seem unrelated to my changes, eg:

```
        --- FAIL: TestAcceptance/acceptance_suite/p_current_cb_current_lc_default/stack_is_created/builder_is_created/build/builder_is_untrusted/additional_tags/pushes_image_to_additional_tags (1.25s)
```

Retriggering didn't help.

Is this because PRs from forks aren't supported, or am I missing something? :-)

**Comment by jjbustamante** [comment]
> CI is failing in ways that seem unrelated to my changes, eg:
> 
> ```
>         --- FAIL: TestAcceptance/acceptance_suite/p_current_cb_current_lc_default/stack_is_created/builder_is_created/build/builder_is_untrusted/additional_tags/pushes_image_to_additional_tags (1.25s)
> ```
> 
> Retriggering didn't help.
> 
> Is this because PRs from forks aren't supported, or am I missing something? :-)

I don't think so, I also saw another PR (#1921) failing for the same reason, I am trying to take a look on what is going on

**Review by jjbustamante — APPROVED** [review]
LGTM

**Comment by edmorley** [comment]
Please can someone merge this for me? It has approval, but I don't have permissions to merge :-)

**Review by jkutner — APPROVED** [review]

**Pull request merged**
