### PR TITLE
Adding a warning message when the SBoM could not be found in the daemon

### LINKED ISSUE #1609: `pack sbom download` command do not inform the user the image must be in the docker daemon
### Summary
When a user tries to download an `sbom` from an image BUT the image is not present in the docker daemon, pack throws an error similar to `ERROR: image 'image' cannot be found: not found` this error confuses the user because if the also try to use `pack inspect` command then they see information about their images.

The reason for this error can be check [here](https://github.com/buildpacks/pack/blob/2e7e9b6253b8bafea39253451fb1d531659a99ea/pkg/client/download_sbom.go#L39)
File: pkg/client/download_sbom.go
```=go
// DownloadSBOM pulls SBOM layer from an image.
// It reads the SBOM metadata of an image then
// pulls the corresponding diffId, if it exists
func (c *Client) DownloadSBOM(name string, options DownloadSBOMOptions) error {
	img, err := c.imageFetcher.Fetch(context.Background(), name, image.FetchOptions{Daemon: options.Daemon, PullPolicy: image.PullNever})
	if err != nil {
		if errors.Cause(err) == image.ErrNotFound {
			return errors.Wrapf(image.ErrNotFound, "image '%s' cannot be found", name)
		}
		return err
	}

        // More code here ...

	return layers.Extract(rc, options.DestinationDir)
}
```

---

##### Steps

1. Check for example if you have an image in your local daemon, if you have it deleted
2. Run `pack sbom download [image]` you should get ERROR: image 'image' cannot be found: not found
3. Run docker `pull image [image]`
4. Run the `pack sbom download [image]` again, the `sbom` or a different messages should be shown.

##### Current behavior

Pack shows an error message that says: `ERROR: image 'image' cannot be found: not found`

##### Expected behavior

Pack shows a warning messages to tell the user that if the image is present in a registry they should run `docker pull` to download the image first, and then try again

---

##### pack info

```=bash
Pack:
  Version:  0.27.0+git-f4f5be1.build-3382
  OS/Arch:  darwin/amd64

Default Lifecycle Version:  0.14.1

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9

Config:
  default-builder-image = "[REDACTED]"
  lifecycle-image = "buildpacksio/lifecycle:0.13.3"
```

##### docker info

``` =bash
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.2)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 37
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.772GiB
 Name: docker-desktop
 ID: DCB7:HPH3:2TFW:5MR7:7GZX:NOVY:3BIB:JPFT:62YQ:OP46:X7EX:OWIN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  192.168.2.20/32
  127.0.0.0/8
 Live Restore Enabled: false
```

### PR DESCRIPTION
**Pull request by jjbustamante**
## Summary
This PR adds a warning message when the command `pack sbom download <image>` is invoked and the image can't be found in the docker daemon.

## Output

Warning message to indicate the user to execute `docker pull <image>` before calling the `pack sbom download` if the image is saved on a registry

#### Before

```=bash
$pack sbom download <image-no-present-in-the-daemon>
ERROR: image '<image-no-present-in-the-daemon>' cannot be found: not found

```

#### After

```=bash
$pack sbom download <image-no-present-in-the-daemon>
Warning: if image is saved on a registry run 'docker pull <image-no-present-in-the-daemon>' before downloading the SBoM
ERROR: image '<image-no-present-in-the-daemon>' cannot be found: not found
```

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

## Related

Resolves #1609

### CODE REVIEW

**Comment by natalieparellano** [comment]
I wonder if it's worth opening another issue to at least investigate why we have this limitation. Copying stuff out of the registry is fast, downloading and then copying stuff out of the daemon is slow. It could be a nice "good first issue".

**Comment by jjbustamante** [comment]
> I wonder if it's worth opening another issue to at least investigate why we have this limitation. Copying stuff out of the registry is fast, downloading the entire image and then copying stuff out of the daemon is slow. It could be a nice "good first issue".

Yeah, I was also planning to do that, this one is just for helping the user to workaround or at least having a hint on what's going on, but, definitly I don't know why we have to extract the sbom from the daemon.

**Comment by jjbustamante** [comment]
It is very annoying this `code coverage` failure when running the build, @natalieparellano could you help me re-running the failed jobs? also if you can assign to me the issue will be awesome!

**Comment by jjbustamante** [comment]
I created another issue  #1615 to investigate and solve if we can retrieve the SBoM from the registry

**Review by jkutner — APPROVED** [review]

**Pull request merged**
