### PR TITLE
Optimization for the performance of addModules(), addExplodedModules(), and addFlattenModules()

### PR DESCRIPTION
**Pull request by edithwuly**
## Summary
Reduce the number of times to traverse buildpack bits. Save about 27% time spent on `addExplodedModules()`. 
Call `NToLayerTar` in goroutine. Save more than half time spent on `addFlattenModules()`.

#### Before
Each buildpack bits will be traversed three times: download, calculate diffID and stream to daemon.
`NToLayerTar` in `addFlattenModules()` is called for each `flattenModule` sequentially.

#### After
The diffID of buildpack will calculated while it is downloaded and saved as a tarfile.
`NToLayerTar` is called in goroutine, referring to addExplodedModules().

## Profiling Result

| command | average time spent on addExplodedModules() before | average time spent on addExplodedModules() after | ratio |
| ----------- | ----------------------------- | --------------------------- | ------------- |
| pack build demo-app --builder cnbs/sample-builder:bionic -p ../samples/java/maven --buildpack paketobuildpacks/java:latest | 3.804439914s | 2.746395149s | 0.72189115 |

| command | average time spent on addFlattenModules() before | average time spent on addFlattenModules() after | ratio |
| ----------- | ----------------------------- | --------------------------- | ------------ |
| pack builder create cnbs/sample-builder:alpine --config builder.toml --flatten | 7.761502674s | 3.751928196s | 0.48340229 |

```
# builder.toml
# Buildpacks to include in builder
[[buildpacks]]
uri = "../samples/buildpacks/hello-processes"

[[buildpacks]]
# Packaged buildpacks to include in builder;
# the "hello-universe" package contains the "hello-world" and "hello-moon" buildpacks
uri = "docker://paketobuildpacks/java:latest"

# Order used for detection
[[order]]
    # This buildpack will create a process type "sys-info" to display runtime information
    [[order.group]]
    id = "samples/hello-processes"
    version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.samples.stacks.bionic"
# This image is used at runtime
run-image = "cnbs/sample-stack-run:bionic"
# This image is used at build-time
build-image = "cnbs/sample-stack-build:bionic"
```

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [ ] No

## Related

Resolves #___

### CODE REVIEW

**Review by natalieparellano — COMMENTED** [review]
Awesome work @edithwuly! Just a note to maintainers, we might want to hold this PR until we can update the benchmark suite [here](https://github.com/buildpacks/pack/pull/1736/files#diff-4ca273c6aff8374837c68a5271d597f762e7ff52489a9c0f25fbce6774bcdeabR116-R118) to show the impact of this change by using a larger buildpack (the samples one is only a few KB it turns out).

**Comment by natalieparellano** [comment]
As per usual it seems Codecov is being a bit too picky here... I wonder if there is a way we can get it to ignore error checks, at least on i/o operations 🤔

**Comment by natalieparellano** [comment]
@buildpacks/platform-maintainers could you please merge this PR first: https://github.com/buildpacks/pack/pull/1773

**Review by jjbustamante — APPROVED** [review]
Great job @edithwuly! Thanks for parallelize the logic for the flatten feature!! ❤️

**Comment by natalieparellano** [comment]
Summarizing offline discussion - I think we're planning to fold this PR into some work that @jjbustamante is doing (as there will likely be a merge conflict)

**Comment by jjbustamante** [comment]
I am closing this PR based on the latest conversation regarding this feature and the after the [RFC](https://github.com/buildpacks/rfcs/pull/290) is approved, we will [remove](https://github.com/buildpacks/rfcs/pull/290#issuecomment-1660543031) most the current implementation and this is not going to be valid anymore

**Pull request closed without merging**
