### PR TITLE
fix: ssh-agent connection on Windows

### PR DESCRIPTION
**Pull request by matejvasek**

### CODE REVIEW

**Comment by matejvasek** [comment]
@jromero @aemengo PTAL

**Comment by aemengo** [comment]
@matejvasek have you already given this a look on a Windows machine? The project has some.

**Comment by matejvasek** [comment]
@aemengo I have not, but colleague of mine @jrangelramos developed and tested this on some Windows VM.
See also https://github.com/knative-sandbox/kn-plugin-func/pull/733

**Comment by jrangelramos** [comment]
+1 
I applied and tested similar fix on func. It works as expected.

**Review by dfreilich — APPROVED** [review]
Thanks for the help with this!

**Pull request merged**
