### PR TITLE
Complete pack-interact workflow

### PR DESCRIPTION
**Pull request by aemengo**
## Summary
Add remaining functionality for pack-interact workflow

This PR kicks continues the following **user workflow**:

When a user runs a pack build like so: `pack build <image-name> --interactive`
Then the user will view the build process through a terminal UI screen
First the `Detecting...` page will show
Then the build "dashboard" page will show

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [ ] No

## Related

Resolves:
https://github.com/buildpacks/pack/issues/1203
https://github.com/buildpacks/pack/issues/1204
https://github.com/buildpacks/pack/issues/1205
https://github.com/buildpacks/pack/issues/1206

### CODE REVIEW

**Review by importhuman — COMMENTED** [review]
Hey @aemengo, this looks insanely cool! Had a couple of questions:

- When starting the build, the initial steps show up in the terminal rather than the dashboard. Is this expected in certain cases? The mockup in the RFC opened up the dashboard immediately, hence my question. (I'd built the image with a Dockerfile before, so there's no pulling all the layers in the attached video)
- I didn't get the detect phase in my dashboard. The 1st video is building an already existing image (though without changes to source code), and the 2nd is building a new image (same name as earlier, but I'd deleted the image before building). 
- In which cases will the plan be shown? I didn't get anything in either case.
- It might be helpful to add a "Press control + c to exit dashboard" message after the build succeeds/fails, since this is meant to be beginner friendly, and also because some folks like me might not realize that the way to exit the dashboard is the same as stopping a running command. 

https://user-images.githubusercontent.com/69148722/135239664-5e946fc4-fca2-43f2-8d32-5715f8e018a2.mov


https://user-images.githubusercontent.com/69148722/135239705-6f7c696a-843f-4ab2-b53f-bef717affde1.mov

**Comment by aemengo** [comment]
@importhuman 
> When starting the build, the initial steps show up in the terminal rather than the dashboard.

Yes, it's expected. Doing the mockup, exactly, was too hard 😕. For now I'm happy to compromise with how it is now.

> I didn't get the detect phase in my dashboard.

That was also intended. I thought it looked better that way because the `plan` is supposed to show the same information. But, I don't feel strongly about this at all.

> In which cases will the plan be shown?

This is definitely not intended. It's always supposed to show. Could be a bug.
The regex is supposed to match `(\S+\/\S+)\s+([\d\.]+)`. Maybe it's because of the lifecycle version? What does the `DETECT` phase logs say without `--interactive`?

> It might be helpful to add a "Press control + c to exit dashboard" message

I think this is a great idea 🙌🏾
If you have a _vision_ for how it should look, maybe you can draft the issue for it.

> this looks insanely cool!

Just you wait. It's gonna be _even cooler!_ 😁

**Comment by importhuman** [comment]
Ah, now that I think about it the mockup would be before adding the feature itself.

> What does the DETECT phase logs say without --interactive?

```
===> DETECTING
3 of 6 buildpacks participating
google.go.runtime  0.9.1
google.go.build    0.9.0
google.utils.label 0.0.1
```

**Comment by aemengo** [comment]
@importhuman Thanks for the providing the output, It was definitely a bug. I wasn't expecting the output to look like that. 
Should be: _Fixed in latest commit_ 👍🏾

**Review by dfreilich — APPROVED** [review]
In terms of code and experience, it's fabulous – thank you so much @aemengo! 
Four small UX nits, but they can definitely be added in a future PR: 
1. I thought that I would be able to do something, while in the interactive mode, by selecting ENTER, or would be able to go into a separate pane, but it seems like I wasn't able to. Is the intention, ultimately, that there would be actions given? 
2. As a result of not being able to change windows, once Build logs scrolled past, I was unable to see them by scrolling up in my terminal, though maybe that's my iterm settings
3. I think having a clear commands window, at the least saying Ctrl+c to close the interactive window, would be great
4. It wasn't initially intuitive that when I exited out of the interactive window, that the build was still continuing behind the scene. That's ok, but I do think signaling that to the user (maybe by printing a message out in the logger when they close the interactive window, that the build is still happening and they can exit out of it by pressing Ctrl+c), would make it much clearer for the users. 

What do you think of that? 

Regardless, this is really great work, and I'm happy to merge it in, once the merge conflicts are resolved

**Comment by aemengo** [comment]
@dfreilich Thanks for reviewing this PR. I really appreciate the time and effort. 

> 1. I thought that I would be able to do something, while in the interactive mode, by selecting ENTER [...] Is the intention, ultimately, that there would be actions given?

Yes, this is the intention. I have a follow-up branch to this PR that will introduce a _"dive"_ panel but delineated by buildpack. Here's an example:

Screen Shot 2021-11-10 at 10 47 54 PM

> 2. As a result of not being able to change windows, once Build logs scrolled past, I was unable to see them by scrolling up in my terminal, though maybe that's my iterm settings

This will also be fixed in the follow-up branch mentioned above.

> 3. I think having a clear commands window, at the least saying Ctrl+c to close the interactive window, would be great

I share the sentiment, but I simply haven't come up with the UX yet. It will definitely come up in a subsequent PR though.

> 4. It wasn't initially intuitive that when I exited out of the interactive window, that the build was still continuing behind the scene. [...].

That's something I didn't think of.. Would definitely like to address this is in a subsequent PR.

**Pull request merged**
