### PR TITLE
Support Platform APIs 0.5,  0.6

### PR DESCRIPTION
**Pull request by dwillist**
## Summary
implement changes needed to support platform api `0.6`, Need to wait for a lifecycle release with buildpacks/lifecycle#520 to be merged and released before writing acceptance tests.

Really this PR just makes the following changes in the codebase:  
- Remove process type defaults for platform API 0.6

### CODE REVIEW

**Comment by dfreilich** [comment]
If there isn't expected to be a lifecycle update with https://github.com/buildpacks/lifecycle/pull/520, should we defer this to the next milestone?

**Comment by dwillist** [comment]
@dfreilich sounds good 👍

**Comment by dfreilich** [comment]
Given the release of `lifecycle v0.11.1` with the required change, this probably can be undrafted. @dwillist Is there any additional work that needs to be done to bring it up to spec, or should we start reviewing it?

**Comment by aemengo** [comment]
@jromero

> Is this really ready to merge […]

The conversation happened out of band, but word was it’s “just waiting for reviews”

**Review by dfreilich — APPROVED** [review]
Overall, this looks great! 

Quite a few of the changes were in adding a space before a comment, so there were fewer changes than I expected, and I'm sorry we didn't merge it in earlier!

**Pull request merged**
