### PR TITLE
Fix project.toml build env to match spec

### PR DESCRIPTION
**Pull request by jkutner**
## Summary

Change the parsing of `project.toml`'s `io.buildpack.build.env` to match the [project descriptor spec](https://github.com/buildpacks/spec/blob/main/extensions/project-descriptor.md#iobuildpacksbuildenv-optional)

https://cloud-native.slack.com/archives/C033DV9EBDF/p1657116095577129

#### Before

```toml
[[io.buildpacks.env.build]]
name = "JAVA_OPTS"
value = "-Xmx300m"
```

#### After

```toml
[[io.buildpacks.build.env]]
name = "JAVA_OPTS"
value = "-Xmx300m"
```

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

### CODE REVIEW

**Comment by jromero** [comment]
Although I agree with this change, this may be considered a breaking change. I'd want to take a deeper look into the reasoning for the change, it's potential impact and mitigation strategies.

**Comment by samj1912** [comment]
As discussed in the WG we cannot make this change directly since this is an end-user breaking change and the current implementation is mimicked by other platforms like kpack as well. If we do change it, we should support both the current and the future version of this key.

**Comment by jromero** [comment]
@jkutner Can you update this PR with backward compatibility support?

I would envision that we would warn about the misuse of the invalid namespace and that the support may be removed at any point in the future.

@samj1912 was there a timeframe for support of the invalid key?

**Comment by samj1912** [comment]
@jromero I would prefer if we soften that warning. Since this is an end user change that we inadvertently implemented in both pack and kpack I would like us to keep this key around at least until project descriptor 0.3.

**Comment by jkutner** [comment]
@jromero @samj1912 i've updated this to include backwards compat

**Review by samj1912 — APPROVED** [review]

**Comment by jkutner** [comment]
@jromero can you give this a look-see?

**Review by jromero — APPROVED** [review]
LGTM!

**Pull request merged**
