### PR TITLE
Improve CLI documentation for pack build --tag

### LINKED ISSUE #1136: Improve CLI documentation for the `pack build --tag` flag
### Description
We do not specify anywhere that this needs to be a full image name (`repo/image:tag`) vs just the final `:tag` portion. 

### Proposed solution
Add some guiding documentation to this flag

### Additional context
https://buildpacks.slack.com/archives/CD61YAG69/p1618506243015800

### PR DESCRIPTION
**Pull request by importhuman**
Closes #1136

Signed-off-by: Ujjwal Goyal <importujjwal@gmail.com>

## Summary
Adds a line describing the format of tags to be supplied to `pack build image --tag`

## Documentation

- Should this change be documented?
    - [ ] Yes
    - [x] No

## Related

Resolves #1136

### CODE REVIEW

**Review by aemengo — APPROVED** [review]
To be honest, I'm a _slightly, slightly_ conflicted by this. Although the help message is correct, it implies that pack is treating a "tag" differently than other tools in the ecosystem. And it's not.

**Comment by importhuman** [comment]
@aemengo not sure I understand, can you please elaborate? 😅 Any changes you'd suggest?

**Comment by jromero** [comment]
> To be honest, I'm a _slightly, slightly_ conflicted by this. Although the help message is correct, it implies that pack is treating a "tag" differently than other tools in the ecosystem. And it's not.

@aemengo, I see where you are coming from. This isn't the first time this confusion has come up. I've opened a discussion for this topic. https://github.com/buildpacks/community/discussions/128#discussion-3537051

At this point, I'd like to consider keeping that discussion out of this PR and focus on the clarification it's provided for how the implementation currently exists.

**Review by jromero — APPROVED** [review]

**Comment by jromero** [comment]
Accepting as-is for now but heavily considering a change to it's implementation to support "true" tags are defined by the OCI spec. See https://github.com/buildpacks/community/discussions/128#discussion-3537051

**Pull request merged**
