### PR TITLE
Pack loses the names of buildpacks

### LINKED ISSUE #1217: Pack loses the names of buildpacks
### Summary
1. `pack buildpack inspect` does not print the names of component buildpacks.
2. `pack builder inspect` does not print the names of any buildpacks
3. When a multibuildpack is packaged only the name of the top-level buildpack in recorded in the `io.buildpacks.buildpack.layers` label
4. When a builder is packaged none of the buildpack names are recorded in the `io.buildpacks.buildpack.layers`

---

##### Steps

1. Observe that both the [Paketo Java Buildpack](https://github.com/paketo-buildpacks/java/blob/main/buildpack.toml#L19) and one of it's children, the [Paketo JMX Buildpack](https://github.com/paketo-buildpacks/jmx/blob/main/buildpack.toml#L19), have `name`s in their respective `buildpack.toml` files
2. Observe that the Paketo JVM Buildpackage contains a name
```
> pack buildpack inspect gcr.io/paketo-buildpacks/jmx
Inspecting buildpack: gcr.io/paketo-buildpacks/jmx
...
Buildpacks:
  ID                           NAME                        VERSION        HOMEPAGE
  paketo-buildpacks/jmx        Paketo JMX Buildpack        3.1.2          https://github.com/paketo-buildpacks/jmx
```
```
> docker pull gcr.io/paketo-buildpacks/jmx
> docker inspect gcr.io/paketo-buildpacks/jmx | jq -r '.[0].Config.Labels."io.buildpacks.buildpack.layers"' | jq -r
{
  "paketo-buildpacks/jmx": {
    "3.1.2": {
      "api": "0.6",
      "stacks": [
        {
          "id": "io.buildpacks.stacks.bionic"
        },
        {
          "id": "org.cloudfoundry.stacks.cflinuxfs3"
        }
      ],
      "layerDiffID": "sha256:c332cab6dd00a6907d9d16a7189340f79a58b09cc3003dda12d70a7e80427231",
      "homepage": "https://github.com/paketo-buildpacks/jmx",
      "name": "Paketo JMX Buildpack"
    }
  }
}
```
3. Observe that the name is lost when this buildpack in included in the Paketo Java Buildpack
```
> pack buildpack inspect gcr.io/paketo-buildpacks/java
Inspecting buildpack: gcr.io/paketo-buildpacks/java
...

Buildpacks:
  ID                                                  NAME                         VERSION        HOMEPAGE
...
  paketo-buildpacks/java                              Paketo Java Buildpack        5.9.1          https://github.com/paketo-buildpacks/java
  paketo-buildpacks/jmx                               -                            3.1.2          https://github.com/paketo-buildpacks/jmx
```
```
> docker pull gcr.io/paketo-buildpacks/java
> docker inspect gcr.io/paketo-buildpacks/java | jq -r '.[0].Config.Labels."io.buildpacks.buildpack.layers"' | jq -r
{
...
  "paketo-buildpacks/java": {
    "5.9.1": {
      "api": "0.6",
      "order": [
        {
          "group": [...]
        }
      ],
      "layerDiffID": "sha256:214d0d5507ac54d7fc3b279f40a980714ff8986903405460f48f0c4f6fa81de7",
      "homepage": "https://github.com/paketo-buildpacks/java",
      "name": "Paketo Java Buildpack"
    }
  },
  "paketo-buildpacks/jmx": {
    "3.1.2": {
      "api": "0.6",
      "stacks": [
        {
          "id": "io.buildpacks.stacks.bionic"
        },
        {
          "id": "org.cloudfoundry.stacks.cflinuxfs3"
        }
      ],
      "layerDiffID": "sha256:c332cab6dd00a6907d9d16a7189340f79a58b09cc3003dda12d70a7e80427231",
      "homepage": "https://github.com/paketo-buildpacks/jmx"
    }
  },
  ```
  
  4. Observe that all names are lost when the Java buildpack is included in a bulider
  ```
  > pack builder inspect paketobuildpacks/builder:base
  ...
  Buildpacks:
  ID                                                  NAME        VERSION        HOMEPAGE
  ...
  paketo-buildpacks/java                              -           5.9.1          https://github.com/paketo-buildpacks/java
  paketo-buildpacks/java-native-image                 -           5.4.0          https://github.com/paketo-buildpacks/java-native-image
  paketo-buildpacks/jmx                               -           3.1.2          https://github.com/paketo-buildpacks/jmx
```

##### Current behavior
Names are lost.

##### Expected behavior
Names of all buildpacks are preserved in `io.buildpacks.buildpack.layers` and displayed by the relevant `pack inspect` commands.

---

##### pack info
```
> pack version
0.19.0+git-360dbae.build-2550
```

##### docker info
N/A

### PR DESCRIPTION
**Pull request by haliliceylan**
Signed-off-by: Halil İbrahim ceylan <acolops@gmail.com>

## Summary
When using `pack builder create` and `pack buildpack package`, `ExtractBuildpacks` function was not reading the name variable if the buildpack was down-levels, I fixed this. Additional information is in the issue #1217

#### Before
Screen Shot 2021-08-11 at 19 50 59

#### After
Screen Shot 2021-08-11 at 19 46 35

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [x] No

## Related

Resolves #1217

### CODE REVIEW

**Comment by dfreilich** [comment]
Thanks for the PR, @haliliceylan ! It looks like there needs to be some changes in the acceptance tests, particularly with the `inspect_builder` tests.  To fix those, you'll probably have to change a lot of the files in https://github.com/buildpacks/pack/tree/main/acceptance/testdata/pack_fixtures, and then put the original ones into the https://github.com/buildpacks/pack/tree/main/acceptance/testdata/pack_previous_fixtures_overrides directory(so that the `compatibility` tests, which ensures that older visions of pack work, pass). If that's too much, we can do it in a polish PR.

**Comment by haliliceylan** [comment]
I did not get it, some acceptance test are passing, but some of them are not passing like combo-acceptance-test. What i did wrong @dfreilich , @jromero ?

**Comment by haliliceylan** [comment]
I copied all orginal ones into `pack_previous_fixtures_overrides` seems not working let me check compability test code.

**Comment by haliliceylan** [comment]
I think compability tests are not pickup `pack_previous_fixtures_overrides` directory default. I am open to any suggestion.

**Pull request merged**
