### PR TITLE
Show detect screen during detect phase

### PR DESCRIPTION
**Pull request by aemengo**
### Visually depict pack build: _detect phase_

This PR kicks off the _pack-interact_ epic and proposes the following **user workflow**:

When a user runs a pack build like so: `pack build <image-name> --interactive`
Then the user will view the build process through a terminal UI screen

Currently only the `Detecting...` page will show

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [ ] No
    - [x] Not yet

## Related

Resolves: https://github.com/buildpacks/pack/issues/1201

### CODE REVIEW

**Comment by jromero** [comment]
@aemengo, what's the state of this PR? I've tried running it and the UI looks nice but I can see a few things having issues.

1. The screen doesn't seem to clear certain sections properly ending up with a "BUILDING**NG**". (See screenshots.)
2. The workflow tends to halt at "EXPORTING" and never proceeds until I `CTRL+C`.

Also, I notice that there are a few `TODO`s in the code.

Is this ready for review or maybe it should be in a draft state? How much focus do we need to put on it at the moment?

image

**Comment by aemengo** [comment]
@jromero

> What's the state of this PR?

My hope is that it is "ready for review". I'm currently soliciting feedback.

> The screen doesn't seem to clear certain sections properly ending up with a "BUILDINGNG". (See screenshot)

Thanks for bringing it up. Unfortunately, I did not (_and still do don't_) see this behavior. May I ask how you're running the build?

> The workflow tends to halt at "EXPORTING" and never proceeds until I CTRL+C.

Again, I'm not really sure what you're seeing. You simply need to run `pack build <image-name> --interactive`. The only words that should be visible is "Detecting...".
Happy to look at this with you.

> There are a few TODOs in the code. How much focus do we need to put on it at the moment?

The TODOs were reminders to create subsequent issues, not to be handled this one. I can remove the TODOs, if needed. There are a few more PRs to make before the user workflow is completed. The aim of this is PR is to make sure that the abstractions are correct, so that I don't have to keep rewriting certain parts. If this PR is merged (_or deemed acceptable_), I can _immediately_ work on the follow-up issues that will complete mockup laid out in the RFC.

**Comment by jromero** [comment]
> @jromero
> 
> > What's the state of this PR?
> 
> My hope is that it is "ready for review". I'm currently soliciting feedback.
> 
> > The screen doesn't seem to clear certain sections properly ending up with a "BUILDINGNG". (See screenshot)
> 
> Thanks for bringing it up. Unfortunately, I did not (_and still do don't_) see this behavior. May I ask how you're running the build?
> 

Here's a recording of what I see: https://asciinema.org/a/friKslqt0jNVVRrogauRJw2qy

`pack-dev` is...
```
❯ which pack-dev
/usr/local/bin/pack-dev

❯ ls -al /usr/local/bin/pack-dev
lrwxr-xr-x  1 jromero  admin  43 Nov 19  2020 /usr/local/bin/pack-dev -> /Users/jromero/dev/buildpacks/pack/out/pack
```

This is on `fish` but there is no difference on `bash`. Also, using `iTerm 2`. Also, tried different window sizes - no change. Anything else that might help troubleshoot this? 

> > The workflow tends to halt at "EXPORTING" and never proceeds until I CTRL+C.
> 
> Again, I'm not really sure what you're seeing. You simply need to run `pack build <image-name> --interactive`. The only words that should be visible is "Detecting...".
> Happy to look at this with you.
> 

HMU if you want to pair on it.

> > There are a few TODOs in the code. How much focus do we need to put on it at the moment?
> 
> The TODOs were reminders to create subsequent issues, not to be handled this one. I can remove the TODOs, if needed. There are a few more PRs to make before the user workflow is completed. The aim of this is PR is to make sure that the abstractions are correct now, while the costs of changing them is lower. If this PR is merged (_or deemed acceptable_), I can _immediately_ work on the follow-up issues that will complete mockup laid out in the RFC.

I would prefer that a) they be removed or b) they link to an issue. Your choice. 😄

**Comment by aemengo** [comment]
TODOs linked in latest commit. Will contact you about pre-existing UI errors tomorrow.

**Pull request merged**
