### PR TITLE
Fix: when running restore, provide creds for run image if there are r…

### PR DESCRIPTION
**Pull request by natalieparellano**
…un image extensions

Otherwise the restorer could fail to find the run image, resulting in unexpected behavior

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [ ] No

## Related

Resolves #___

### CODE REVIEW

**Comment by natalieparellano** [comment]
Will undraft once tests are added

**Comment by natalieparellano** [comment]
See https://github.com/buildpacks/lifecycle/pull/1134#issuecomment-1614781077 for further evidence that this fix does what it is supposed to

**Review by jjbustamante — APPROVED** [review]
Nice.

**Review by joe-kimmel-vmw — APPROVED** [review]
LGTM

**Review by jkutner — APPROVED** [review]

**Pull request merged**
