### PR TITLE
Validate contents of builder.toml

### PR DESCRIPTION
**Pull request by supra08**
@natalieparellano As per the comments on #535 and the edits you suggested in this branch, I guess its good. I closed the previous PR because of a messed up git history.
It is updated with the correct test validation strings.
Thanks!

### CODE REVIEW

**Comment by natalieparellano** [comment]
Hi @supra08 - thanks for updating your PR. I was curious why your assertion [here](https://github.com/buildpacks/pack/pull/556/files#diff-f281adcebf7016de8c1a237adaf6ddedR121) was different from the suggestion I made [here](https://github.com/buildpacks/pack/pull/535#discussion_r401032540) (you have `buildpack` instead of `buildpacks.url`) - this led me to investigate more carefully what [`ParseUndecodedKeys`](https://github.com/buildpacks/pack/pull/556/files#diff-fd12d333394af3a56cb11d0df8526102R11) is doing and I think there is a bug. It's a bit tricky to explain so I am going to send you another PR with detailed comments. Please review and let me know what you think - once this last bit is resolved (assuming all the automated checks are happy) I can recommend that we merge.

**Comment by supra08** [comment]
Yes @natalieparellano I was just about to point out this bug and wanted to open an issue for this.
I'll have a look at your PR and let you know.

**Comment by natalieparellano** [comment]
Thanks @supra08! This looks good to me. @jromero I think this is ready for your review.

**Comment by jromero** [comment]
# ✅ Accepted

### Table

```
$ cat ../samples/builders/alpine/builder.toml
# Buildpacks to include in builder
[[buildpacks]]
id = "io.buildpacks.samples.java-maven"
version = "0.0.1"
uri = "../../buildpacks/java-maven"

[[buildpackssssssss]]
id = "io.buildpacks.samples.kotlin-gradle"
version = "0.0.1"
uri = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
image = "cnbs/sample-package:hello-universe"

$  ./out/pack create-builder my-builder -b ../samples/builders/alpine/builder.toml 
ERROR: invalid builder toml: parse contents of '../samples/builders/alpine/builder.toml': unknown configuration element buildpackssssssss in ../samples/builders/alpine/builder.toml
```

### Keys

```
$ cat ../samples/builders/alpine/builder.toml
# Buildpacks to include in builder
[[buildpacks]]
id = "io.buildpacks.samples.java-maven"
version = "0.0.1"
uri = "../../buildpacks/java-maven"

[[buildpacks]]
identifier = "io.buildpacks.samples.kotlin-gradle"
verson = "0.0.1"
url = "../../buildpacks/kotlin-gradle"

[[buildpacks]]
image = "cnbs/sample-package:hello-universe"

$  ./out/pack create-builder my-builder -b ../samples/builders/alpine/builder.toml 
ERROR: invalid builder toml: parse contents of '../samples/builders/alpine/builder.toml': unknown configuration elements buildpacks.identifier, buildpacks.verson, buildpacks.url in ../samples/builders/alpine/builder.toml
```

**Comment by jromero** [comment]
Thanks for the contribution @supra08 (and @natalieparellano for the support)!  Keep it up!

**Pull request merged**
