### PR TITLE
Get rid of the old  --flatten --flatten-include feature to have a clean baseline for the new --flatten one

### PR DESCRIPTION
**Pull request by dlion**
## Summary
This is the starting point for the [Flatten RFC](https://github.com/buildpacks/rfcs/pull/290).
The aim of this PR is to get rid of the old code about the flatten feature and re-implement it according to https://github.com/buildpacks/rfcs/pull/290

#### Before

`pack build --experimental --flatten --flatten-include`

#### After

`pack build --flatten`

## Documentation

- Should this change be documented?
    - [ ] Yes, see #___
    - [X] No

### CODE REVIEW

**Comment by natalieparellano** [comment]
Just to clarify, is the aim to re-implement the feature according to https://github.com/buildpacks/rfcs/pull/290 before we ship another `pack`?

**Comment by jjbustamante** [comment]
> Just to clarify, is the aim to re-implement the feature according to [buildpacks/rfcs#290](https://github.com/buildpacks/rfcs/pull/290) before we ship another `pack`?

Yes, that's the idea 😄 . I think @dlion was so happy to remove code that the name of the PR indicates we want to remove the feature

**Comment by dlion** [comment]
Ups, yeah thanks for clarifying @natalieparellano ! ❤️ 
I edited the title and enriched the description.
Indeed this is just the first step which will allow us to start from scratch for the new implementation 😄

**Comment by jjbustamante** [comment]
Closing this PR in favor of #1985

**Pull request closed without merging**
